Mark as BROKEN-hppa, since last update to 3.3.4. undefined reference to `std::auto_ptr<geos::geom::Envelope>::~auto_ptr()'
Written by: Landry Breuil <landry@openbsd.org>