BROKEN-hppa =   libQtWebKit.so.3.0: undefined reference to `__sync_sub_and_fetch_4'
No point in trying to build it for days before seeing it failing horribly
because hppa/atomic ops/webkit... there might be an easy fix/workaround;
but right now hope is lost.

Written by: Landry Breuil <landry@openbsd.org>