update to jekyll-1.0.0
Some notes when upgrading: the --server and --build flags have been turned
into subcommands. So use 'jekyll server' from now on. Also '--auto' was
changed to '--watch'
And you need to make sure the excludes in your _config.yml is an array or
you'll end up with: error: undefined method `glob_include?' for "foo".

ok jeremy@

Written by: Jasper Lievisse Adriaanse <jasper@openbsd.org>