Switch xulrunner to gcc4 on amd64, doesn't link with llvm 3.7.1.
../../layout/svg/nsSVGFilterFrame.o: In function `nsSVGFilterFrame::GetFilterContent(nsIContent*)':
/usr/obj/ports/xulrunner-24.8.0/mozilla-esr24/layout/svg/nsSVGFilterFrame.cpp:(.text._ZN16nsSVGFilterFrame16GetFilterContentEP10nsIContent+0x32): undefined reference to `nsSVGFE::COMTypeInfo<int>::kIID'
/usr/bin/ld: ../../layout/svg/nsSVGFilterFrame.o: relocation R_X86_64_PC32 against `_ZN7nsSVGFE11COMTypeInfoIiE4kIIDE' can not be used when making a shared object; recompile with -fPIC

(of course -fPIC is used when compiling nsSVGFilterFrame.o, so i'll just
blame llvm/ld and move on to other things. xulrunner is a dead end anyway)

Written by: Landry Breuil <landry@openbsd.org>